version: "3.4"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
